#!/usr/bin/env python

import json
import os
import sys

import requests

# ti = thread_info
# posturl =


def appendThreadInfoSheet(ti):
    data = [channel_id, ti.id, ti.topic, ti.name, ti.date, 0]
    req = requests.post(url=gas_post_url, data=json.dumps(data))
    return req.text


def push(thread_info):
    result = appendThreadInfoSheet(thread_info)
    if result == "0":
        os.exit(0)
    else:
        os.exit(1)


if __name__ == "__main__":
    channel_id = os.environ["channel_id"]
    gas_post_url = os.environ["gas_post_url"]
    thread_info = json.loads(sys.stdin.read())
    push(thread_info)
