name: CI

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: git clone --depth=1 https://${{ secrets.GITHUB_TOKEN }}github.com/shinhwagk/${{ secrets.REPO }} /AAAA
